version: 2.1

jobs:
  run_tests:
    parameters:
      ruby_version:
        description: "Version of Ruby to run tests in"
        type: string
      rack_version:
        description: "More or less the Rack version we want to test against"
        type: string
    environment:
      TEST_WITH_RACK: << parameters.rack_version >>
    docker:
      - image: ruby:<< parameters.ruby_version >>
    steps:
      - checkout
      - run: apt-get update -qq
      - run: apt-get install -y -qq libyaml-dev
      - run: bundle install
      - run: bundle exec rake

workflows:
  version: 2
  test:
    jobs:
      - run_tests:
          matrix:
            parameters:
              ruby_version: ["3.0", "3.1", "3.2", "3.3"]
              rack_version: ["1.6.0", "2.1.0", "2.2.0", "3.0.0"]
