name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  tests:
    strategy:
      matrix:
        ruby_version:
          - "3.2"
          - "3.3"
          - "3.4"
        rack_version:
          - "2.2.0"
          - "3.0.0"
          - "3.1.0"
          - "3.2.0"
    name: Ruby ~> ${{ matrix.ruby_version }}; Rack ~> ${{ matrix.rack_version }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      TEST_WITH_RACK: ${{ matrix.rack_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake
