name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        ruby_version:
          - "3.1"
          - "3.2"
          - "3.3"
        rack_version:
          - "1.6.0"
          - "2.1.0"
          - "2.2.0"
          - "3.0.0"
    name: Ruby ~> ${{ matrix.ruby_version }}; Rack ~> ${{ matrix.rack_version }}
    runs-on: ubuntu-latest
    env:
      TEST_WITH_RACK: ${{ matrix.rack_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          apt-get: _update_ libyaml-dev
      - run: bundle exec rake
